### ISSUE TITLE
Question: Recommended approach when using a custom FuelManager instance

### ISSUE THREAD

**Issue by ppslim** [KennethWussmann/mock-fuel#29]
My application creates a `FuelManager` per instance and is marked private. This is done as I may be talking to multiple REST endpoints, each with unique request/response interceptors.

```kotlin
class sample {
    private val fuel = FuelManager()
}
```

This limits me currently from annotating my test classes with `MockFuelExtension`, though mostly on the part of junit not providing any assured order of execution for before callback / annotations, preventing me from swapping `Fuel.instance` in any way that would assure this.

I could use a `RuleChain` including with `ExternalResource`, but there is little detail I can find on execution order when used with a `BeforeEachCallback` like in `MockFuelExtension`.

What approaches could I take to mock the client when not using the default instance in this way?

**Comment by KennethWussmann** [comment]
Hey ppslim,
sorry for my late response - somehow missed the notification. 

Thanks for mentioning your use-case. Indeed, the class `MockFuelExtension` might not fit your requirements, but you can still mock your `private val` using a mock library like [mockk](https://github.com/mockk/mockk).

It's important to use a `lazy` in this case, for example:
```Kotlin
class Sample {

    private val fuel by lazy { FuelManager().apply { basePath = "https://api.predic8.de" } }

    fun doRequest(): Boolean {
        val (_, _, result) = fuel.get("/shop/products/62").responseString()
        // do something
        return result is Result.Success
    }
}
```

And in your test, you have to replace that `FuelManager`:
```kotlin
class SampleTest {

    private val mockFuelStore = MockFuelStore()
    private val sample = spyk(Sample(), recordPrivateCalls = true)

    @BeforeEach
    fun setUp() {
        every { sample getProperty "fuel" } returns FuelManager().apply {
			// override the client of the FuelManager
            client = MockFuelClient(mockFuelStore)
            basePath = "http://localhost:8080/"
        }
    }

    @AfterEach
    fun tearDown() {
		// unmockk that sample for the next tests
        unmockkObject(sample)
		// reset the store
        mockFuelStore.reset()
    }

    @Test
    fun `fuel request is successful`() {
        mockFuelStore.enqueue(MockResponse(200, body = "Hello World".toByteArray()))
        val result = sample.doRequest()

        assertTrue(result)
    }

    @Test
    fun `fuel request is unsuccessful`() {
        mockFuelStore.enqueue(MockResponse(500, body = "Internal Server Error".toByteArray()))
        val result = sample.doRequest()

        assertFalse(result)
    }
}
```
