### ISSUE TITLE
Suggested change to param matching

### ISSUE THREAD

**Issue by hemfridsvagen25** [KennethWussmann/mock-fuel#48]
Hi 
I like this lib and have used it with success. But I needed to do a small modification to have the matcher match on params.  Since fuel changes the paramlist to url params.
What i did is added a matching for the url params if paramlist was null
In MockFuelStore.kt line 71
changed queryParams to queryParams?.map { Pair(it.first, it.second.toString()) }
And in MockRequestMatcher.kt line 31
changed queryParams != null && request.parameters != queryParams -> false
to queryParams != null && mapQueryParams(request.url.query) ?: request.parameters != queryParams -> false

I hope this does not break anything.
I tried to make a pull request but I am new to github so I did not manage to do it.

Best regards
Mats Olsson

**Comment by KennethWussmann** [comment]
Hey @hemfridsvagen25,
thanks for your report, I'll take a closer look at it.

**Comment by KennethWussmann** [comment]
Hey @hemfridsvagen25,
I was able to reproduce your bug and it will be fixed in v1.3.0.
Thank you!
