### ISSUE TITLE
Passthrough function

### ISSUE THREAD

**Issue by hemfridsvagen25** [KennethWussmann/mock-fuel#49]
Hi I have used your lib with great success.  I happened on a case where i did not want to mock all requests. So I made a way to do a real http call when returned status is set to 999.  Using this I can mock parts of a call chain while letting through the one that i want to test the real response from.

Could not create a pull request.  New to GitHub so I probably made a misstake.  But the change is small so i paste it in here.

New MockFuelClient.kt
package net.wussmann.kenneth.mockfuel

import com.github.kittinunf.fuel.core.Client
import com.github.kittinunf.fuel.core.FuelManager
import com.github.kittinunf.fuel.core.Request
import com.github.kittinunf.fuel.core.Response
import com.github.kittinunf.fuel.toolbox.HttpClient
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import net.wussmann.kenneth.mockfuel.data.MockRequestMatcher

const val PASSTHROUGH = 999
/**
 * Implementation of the Fuel http client that doesn't emit requests to any external services
 */
class MockFuelClient(private val mockFuelStore: MockFuelStore) : Client {

    private val realClient: Client = HttpClient(FuelManager.instance.proxy, hook = FuelManager.instance.hook)
    override fun executeRequest(request: Request): Response {
        val response = mockFuelStore.findResponse(request)
        val newResponse = if (response.statusCode == PASSTHROUGH) {
            realClient.executeRequest(request)
        } else {
            null
        }
        mockFuelStore.recordedRequests.add(MockRequestMatcher.from(request))
        if (response.delay > 0) {
            runBlocking {
                delay(response.delay)
            }
        }
        return newResponse ?: response.toResponse(request.url)
    }
}

And added test  (to swedish newspaper)
    @Test
    fun `Should run real request for matching request status 999`() {
        mockFuelStore.on(host = "www.dn.se", path = "/") {
            MockResponse(statusCode = PASSTHROUGH)
        }
        FuelManager.instance.basePath = "http://www.dn.se"
        val response = instance.executeRequest(Fuel.get("/"))

        assertEquals(301, response.statusCode)
    }

**Comment by KennethWussmann** [comment]
Hey @hemfridsvagen25,
glad you like the lib. I agree such a passthrough feature can be helpful. 
The status code looks kind of unintuitive in my opinion.
I'll figure something out and build it into the lib.

Thanks for the feature request,
Kenneth

**Comment by KennethWussmann** [comment]
I added the suggested feature and some info on [how to use it to the readme](https://github.com/KennethWussmann/mock-fuel#pass-through-responses).
Will be available in v1.3.0
